/*
   Given two strings s and t which consist of only lowercase letters.
   String t is generated by random shuffling string s and then add one more letter at a random position.
   Find the letter that was added in t.
*/

function findDifference(s, t) {
  // 'absd' => 'abcda'
  // s = { a:1, b:0, c:0, d:0 }
  let hash = {};
    
  for (let i = 0; i < s.length; i++) {
    let char = s[i];
    if (!hash[char])
      hash[char] = 1;
    else
      hash[char] = hash[char] + 1;
    }
    
  for (let i = 0; i < t.length; i++) {
    let char = t[i];
    if (hash[char])  // true if >= 1
      --hash[char];
    else 
      return char;
    } 
}

// Test
console.log(findDifference('absd', 'abcda')); // a
